import { pgTable, serial, text, integer, real, boolean, timestamp } from "drizzle-orm/pg-core";

export const recurringInvoicesTable = pgTable("recurring_invoices", {
  id: serial("id").primaryKey(),
  userId: text("user_id").notNull(),
  name: text("name").notNull(),
  status: text("status").notNull().default("active"),
  frequency: text("frequency").notNull(),
  dayOfMonth: integer("day_of_month").default(1),
  nextRunDate: text("next_run_date").notNull(),
  endDate: text("end_date"),
  lastGeneratedAt: text("last_generated_at"),
  customerId: integer("customer_id"),
  customerName: text("customer_name"),
  customerEmail: text("customer_email"),
  customerPhone: text("customer_phone"),
  customerAddress: text("customer_address"),
  customerGstin: text("customer_gstin"),
  placeOfSupply: text("place_of_supply"),
  supplyType: text("supply_type").notNull().default("intra"),
  itemsJson: text("items_json").notNull().default("[]"),
  discountType: text("discount_type").notNull().default("flat"),
  discountValue: real("discount_value").notNull().default(0),
  taxPercent: real("tax_percent").notNull().default(0),
  notes: text("notes"),
  paymentTerms: text("payment_terms"),
  showBankDetails: boolean("show_bank_details").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});
